In [1]:
from datascience import *

In [2]:
import random
import numpy as np

In [22]:
# t: inventory
# d: demand of customer (unknown in the first state)
# s: sales in one day
# r: revenue after each day
# p: price
# state (remaining inventory, time before expiration)
# action: increase/decrease/keep the price
# reward: reward: increase revenue, penalty: decrease/unchanged
# transaction prob: increase revenue/decrease/unchanged

In [3]:
def get_dataset(inventory):
    customer_demand = np.empty(shape=0,dtype=int) #create customer demand array
    sales = np.empty(shape=0,dtype=int) #create sales array
    price = np.empty(shape=0,dtype=float) #create price array
    inventory_arr = np.empty(shape=0,dtype=int) #create inventory array
    purchase_prob_arr = np.empty(shape=0,dtype=float)
    date = 30
    date_arr = np.empty(shape=0,dtype=int)
    for day in range(0,31):
        day_demand = random.randint(0,60) #simulate daily demand in a day 
        customer_demand =np.append(customer_demand,day_demand)

        day_price = random.randint(0,3000) /100 #simulate daily price in a day 
        price = np.append(price, day_price)

        #find the probability of customers making the sales and times the day demand to get actual day sale
        purchase_probability = round((-1/900) * (day_price)**2 +1,2) #find the probability of customers purchasing (decaying)
        purchase_prob_arr = np.append(purchase_prob_arr,purchase_probability) #add to the array
        day_sale = round(purchase_probability*day_demand) #calculate the sales
        if day_sale<0: #if there are no customers visit the website/sale yield negative, no sales were made
            day_sale = 0
            sales = np.append(sales, day_sale)
            remaining_inventory = inventory - day_sale
        else:
            remaining_inventory = inventory - day_sale
            if remaining_inventory < 0: #negative inventory, set the day sale to the remaining inventory and recalculate the remaining inventory, which should yield 0
                day_sale = inventory
                remaining_inventory = inventory - day_sale  #recalculate the remaining inventory
            sales = np.append(sales, day_sale) #append the sale to the list

        inventory_arr = np.append(inventory_arr,remaining_inventory) #append the inventory to the array
        inventory = remaining_inventory #update the current inventory
        date_arr = np.append(date_arr,date)
        date-=1
        if inventory == 0:
            break

    revenue = price * sales #calculate the revenue
    table = Table().with_columns (
        'Date', date_arr,
        'Price', price,
        'Customer Demand', customer_demand,
        'Purchase Probability', purchase_prob_arr,
        'Sales', sales,
        'Revenue',revenue,
        'Remaining Inventory', inventory_arr
    )
    #adding the profit column
    revenue_diff_arr = np.array([revenue[0]])
    range_len = len(table.column('Revenue'))-1
    for r in range (0,range_len):
        revenue_diff = table.column('Revenue')[r+1]-table.column('Revenue')[r]
        # print(revenue_diff)
        revenue_diff_arr = np.append(revenue_diff_arr,revenue_diff)
    #print(revenue_diff_arr)
    new_table = table.with_column(
        'Profit',revenue_diff_arr
    )
    return new_table

In [4]:
simulated_dataset = get_dataset(1000)
simulated_dataset.show()

In [5]:
def compare(old,new):
    if old<new:
        return "Increasing"
    elif old>new:
        return "Decreasing"
    else:
        return "Unchanged"

In [6]:
def get_price_table(data):
    price = data.column('Price')
    new_price = np.append(price[1:len(price)+1],0)
    price_table = Table().with_columns(
    'Old Price',price,
    'New Price',new_price
    )
    price_table = price_table.with_column(
    "Comparison", price_table.apply(compare,'Old Price','New Price')
    )
    return price_table

In [7]:
price_table = get_price_table(simulated_dataset)

In [8]:
price_table.show()

Conduct __A/B testing__ to see the chance that the future dataset will likely behave the same as this dataset

* Null Hypothesis: The future data will behave the same

* Alternative: The future data won't behave the same

In [86]:
def difference_of_means(tbl, label_column):
    means_table = tbl.group(label_column, np.average)
    means_array = means_table.column(1)
    return means_array.item(1) - means_array.item(0)

In [92]:
observed_difference = difference_of_means(price_table,'Comparison')
observed_difference

-7.448541666666667

In [93]:
def get_p_value(repetition):
    price_table = get_price_table(simulated_dataset)
    observed_difference = difference_of_means(price_table,'Comparison')
    print(observed_difference)
    differences = make_array()

    # for many iterations
    for i in np.arange(repetition):

        # create a new table whose first column is shuffled category labels and second column is old price in original order
        shuffled_comparison = price_table.sample(with_replacement=False)
        combined = price_table.with_column('Shuffled Comparison', shuffled_comparison.column(2))
        combined = combined.select('Shuffled Comparison', 'Old Price')

        # calculate the value of the test statistic for the shuffled versions
        simulated_difference = difference_of_means(combined, 'Shuffled Comparison')

        # append the outcome to array
        differences = np.append(differences, simulated_difference)
    
    #calculate the p-value
    p_value = np.count_nonzero(differences<=observed_difference)/repetition
    print(differences)
    return p_value

In [94]:
get_p_value(1000)

-7.448541666666667
[  3.46666667e-01  -3.98558333e+00  -2.42008333e+00  -2.25087500e+00
  -3.75437500e+00  -9.17875000e-01   7.60000000e-01   4.24620833e+00
   5.57404167e+00   6.77916667e+00   2.07879167e+00  -6.73941667e+00
   2.19375000e+00  -4.56941667e+00  -3.37333333e+00   1.65254167e+00
  -1.67608333e+00  -1.61279167e+00  -1.08792083e+01  -8.33916667e-01
  -2.65583333e-01  -1.35187500e+00   1.23533333e+00  -1.76779167e+00
  -3.19637500e+00   2.89900000e+00  -1.70191667e+00   1.75070833e+00
   3.26000000e-01  -1.78200000e+00   6.07133333e+00   6.38133333e+00
   3.00104167e+00   4.02275000e+00  -4.76125000e-01  -2.55054167e+00
   1.18495833e+00   5.83041667e-01   2.53666667e-01   7.75500000e-01
   1.24437500e+00   3.45570833e+00  -1.01087500e+00   5.00054167e+00
   3.24129167e+00   4.82229167e+00   4.64275000e+00   1.30379167e+00
  -3.81766667e+00  -5.05637500e+00  -2.58800000e+00  -1.45391667e+00
  -2.36066667e+00   1.71066667e+00  -3.21962500e+00  -3.80087500e+00
  -1.23691667e+00   9.09166667e-02  -3.37075000e+00  -8.72666667e-01
   3.67270833e+00  -3.69108333e+00   1.08550000e+00   2.29191667e+00
   1.76491667e+00  -2.34000000e+00   3.10695833e+00   3.82641667e+00
   4.02208333e-01   2.56962500e+00  -1.02120833e+00  -2.48791667e-01
  -1.22141667e+00  -1.26404167e+00  -5.23916667e-01  -4.85166667e-01
   3.53320833e+00  -1.50429167e+00   2.89641667e+00  -1.72387500e+00
  -2.94708333e+00  -2.89800000e+00  -4.44541667e+00   1.56083333e+00
   4.79708333e-01  -6.13233333e+00   5.81750000e-01   3.64558333e+00
   3.62879167e+00  -5.04541667e-01   3.07854167e+00   2.31775000e+00
  -2.12945833e+00  -2.68358333e+00   1.21208333e+00  -1.03283333e+00
  -1.06383333e+00   2.01679167e+00  -5.22625000e-01   1.57245833e+00
  -2.83212500e+00   3.29812500e+00  -2.45754167e+00   3.46345833e+00
   6.03708333e-01  -4.10958333e+00  -2.34583333e-01  -1.32087500e+00
   1.86825000e+00   5.71416667e-01   2.55283333e+00  -3.60841667e+00
   2.72333333e+00   4.47416667e-01  -1.64508333e+00   2.60450000e+00
  -2.23150000e+00   4.58850000e+00  -3.92875000e+00  -1.97962500e+00
  -6.01479167e+00   3.27291667e-01   1.86308333e+00   9.58916667e-01
  -5.26045833e+00   4.37666667e+00   5.23625000e-01   2.77112500e+00
  -5.08995833e+00   1.08679167e+00  -2.12558333e+00  -4.16383333e+00
   5.35445833e+00  -1.39837500e+00   4.54458333e+00   2.17695833e+00
   5.72645833e+00   3.44083333e-01  -5.23979167e+00  -2.11266667e+00
  -1.36737500e+00  -1.53141667e+00  -4.03791667e-01  -2.91995833e+00
   5.73808333e+00  -4.20583333e-01  -2.74816667e+00  -5.98833333e-01
   2.02712500e+00  -8.14541667e-01  -1.30020833e+00  -7.30583333e-01
  -3.60712500e+00   1.53241667e+00   3.15087500e+00  -5.87208333e-01
  -2.36583333e+00   2.59933333e+00  -1.94475000e+00  -2.53333333e-02
   2.44304167e+00  -2.51954167e+00   2.69233333e+00  -2.16433333e+00
  -4.92916667e-01  -6.62445833e+00  -1.06641667e+00  -1.54820833e+00
  -5.26500000e-01   6.24375000e-01   1.05837500e+00  -1.25758333e+00
  -3.59420833e+00   5.32733333e+00  -3.80862500e+00   1.10358333e+00
   5.37641667e+00  -1.00441667e+00  -6.09229167e+00  -1.49137500e+00
  -1.09291667e-01   1.96641667e+00   6.14625000e+00   1.71970833e+00
  -2.64291667e-01   9.84750000e-01   1.28958333e+00  -1.63475000e+00
   8.18125000e-01   2.41462500e+00   6.70875000e-01  -3.10466667e+00
   3.49187500e+00   1.11391667e+00   2.27383333e+00  -3.41595833e+00
  -2.94191667e+00   1.01250000e-01  -5.27337500e+00   1.08162500e+00
  -1.08062500e+00   2.25575000e+00  -1.71612500e+00  -1.16975000e+00
  -4.87812500e+00   1.98708333e+00   1.22758333e+00   1.39162500e+00
   1.91087500e+00   8.28266667e+00   1.95541667e-01  -5.29083333e-01
   1.53112500e+00  -3.35333333e-01   6.92833333e-01   3.13925000e+00
   7.63875000e-01   2.91062500e+00  -1.23500000e-01  -3.91841667e+00
  -3.03233333e+00   4.13383333e+00  -3.36945833e+00   2.45208333e+00
  -2.22245833e+00   2.77500000e+00  -3.27000000e+00   1.33995833e+00
   7.57741667e+00   2.26995833e+00   2.56704167e+00   3.22191667e+00
   1.28958333e+00  -2.87087500e+00   5.05091667e+00   2.34616667e+00
   4.21650000e+00  -2.26508333e+00  -1.26791667e+00   1.52079167e+00
  -1.84400000e+00  -2.01579167e+00   2.48954167e+00  -1.31829167e+00
  -4.54166667e-01   3.77991667e+00  -2.42525000e+00   3.50220833e+00
   2.94162500e+00   9.35000000e-02   4.01887500e+00   2.04133333e+00
  -9.34666667e-01   8.99500000e-01   2.75820833e+00   2.54637500e+00
   7.16083333e-01   2.51150000e+00  -8.40375000e-01   9.67958333e-01
  -2.24312500e+00   4.70862500e+00   2.30225000e+00  -6.02083333e-02
  -6.15000000e-02  -1.41129167e+00   2.51020833e+00  -7.55125000e-01
  -8.40375000e-01  -6.77300000e+00   2.15241667e+00  -1.04058333e+00
  -1.87370833e+00   9.16291667e-01   2.28545833e+00   2.24541667e+00
   9.09833333e-01   2.19762500e+00   2.68458333e+00  -1.98350000e+00
  -1.23304167e+00  -1.21625000e+00  -4.25683333e+00   5.93054167e+00
  -3.35137500e+00  -7.29291667e-01  -1.05091667e+00   2.42366667e+00
  -3.22737500e+00   6.76666667e-02   4.63887500e+00   3.12891667e+00
   6.48079167e+00   1.15912500e+00   3.10954167e+00   2.77758333e+00
  -3.53220833e+00   4.38570833e+00  -2.43687500e+00   1.31800000e+00
   3.03850000e+00   8.78833333e-01   3.54612500e+00   1.20433333e+00
  -2.04937500e+00  -9.87625000e-01  -2.82308333e+00   4.55879167e+00
  -2.83666667e-01   1.88116667e+00  -3.95845833e+00  -5.80295833e+00
  -3.17700000e+00   3.97041667e-01   3.06045833e+00   4.81325000e+00
   9.34375000e-01  -6.41391667e+00   6.34516667e+00   1.88504167e+00
   2.65291667e-01   4.45545833e+00  -2.42008333e+00   2.71945833e+00
   5.90791667e-01  -5.38575000e+00  -5.71708333e-01  -7.61583333e-01
  -7.43500000e-01  -1.84529167e+00  -6.88666667e+00  -3.53995833e+00
   2.24025000e+00   1.42650000e+00  -3.25579167e+00  -2.48791667e-01
  -2.03645833e+00   4.21004167e+00   5.73333333e-02  -2.26379167e+00
   3.47958333e-01  -1.82720833e+00   6.76666667e-02  -1.08450000e+00
  -3.20412500e+00   5.09870833e+00  -2.24570833e+00   2.03229167e+00
  -3.80216667e+00   1.34770833e+00   2.95970833e+00  -1.11420833e+00
   8.01333333e-01  -1.59212500e+00   4.08666667e-01  -4.67145833e+00
  -1.04187500e+00  -4.62754167e+00   6.03129167e+00   4.69570833e+00
   3.48800000e+00   4.31208333e+00  -4.39504167e+00   5.83237500e+00
  -2.25087500e+00  -6.18208333e-01  -4.32208333e-01  -4.84712500e+00
   2.33325000e+00  -1.42291667e+00  -3.57291667e-01   4.46125000e-01
  -4.25683333e+00  -4.21250000e-02   2.25187500e+00   5.06833333e-01
  -4.23616667e+00  -1.13616667e+00   4.16225000e+00  -3.75566667e+00
  -4.97370833e+00  -2.92512500e+00   5.32087500e+00  -4.62754167e+00
  -5.63504167e+00   4.83520833e+00  -7.42012500e+00  -3.59875000e-01
  -2.85020833e+00   7.70333333e-01  -2.53116667e+00   4.70604167e+00
   7.98750000e-01   3.10050000e+00   4.65179167e+00   3.42341667e+00
   5.43000000e-01  -1.07545833e+00  -1.88920833e+00   4.44254167e+00
   2.58125000e+00  -2.24183333e+00  -4.26200000e+00   2.23508333e+00
   2.12658333e+00  -7.88708333e-01  -2.94320833e+00   2.60579167e+00
   1.46266667e+00   4.80550000e+00   1.27150000e+00   4.66791667e-01
   4.25654167e+00  -5.28112500e+00   1.71712500e+00   7.84541667e-01
  -2.79791667e-01  -2.12816667e+00   1.72291667e-01  -3.05625000e-01
   5.01666667e-01   1.69000000e+00  -4.06375000e-01  -7.33875000e+00
   1.16170833e+00   1.95608333e+00  -5.82041667e-01  -6.73750000e-01
  -6.55987500e+00  -2.21083333e+00   6.24375000e-01   1.61508333e+00
  -4.96466667e+00  -1.85175000e+00  -1.41583333e-01  -3.05687500e+00
   4.46320833e+00   2.44045833e+00  -3.52833333e+00  -2.35875000e-01
   7.56320833e+00   2.62708333e-01  -4.66887500e+00   9.07250000e-01
  -2.00416667e+00  -1.48233333e+00  -5.22041667e+00   4.54458333e+00
  -1.20979167e+00   1.89537500e+00   1.38645833e+00  -1.05479167e+00
  -2.24183333e+00   2.77370833e+00  -1.54175000e+00  -5.02537500e+00
  -1.74325000e+00   9.40833333e-01   3.94525000e+00   1.78300000e+00
   9.17583333e-01  -5.77066667e+00   1.25987500e+00   5.65283333e+00
  -1.44100000e+00  -9.38541667e-01   5.19558333e+00   1.37870833e+00
  -4.49000000e-01  -2.02483333e+00  -1.64833333e-01  -9.19166667e-01
   6.33095833e+00   3.45054167e+00  -2.19275000e+00   5.93375000e-01
   2.37587500e+00   3.29166667e+00   8.12958333e-01  -2.54150000e+00
   1.28829167e+00  -5.42000000e-01   4.05416667e-02   6.26766667e+00
   1.43037500e+00   2.76250000e-02  -2.89800000e+00   2.92870833e+00
   9.87333333e-01   2.50416667e-02   4.06537500e+00  -3.22416667e-01
  -2.61254167e+00  -9.06250000e-01   6.23083333e-01   1.01704167e+00
  -2.17208333e+00  -2.04679167e+00   3.33945833e+00   3.88841667e+00
   4.06795833e+00  -1.50816667e+00   2.55283333e+00  -7.57708333e-01
   1.14104167e+00   2.18791667e-01  -7.77083333e-01   1.72487500e+00
   7.80000000e-02   4.26750000e-01  -5.43291667e-01   5.86250000e-02
   7.28333333e-02  -1.49654167e+00   1.14879167e+00  -1.73162500e+00
   1.10291667e-01   8.57500000e-02   6.46333333e-01  -2.56216667e+00
  -4.72312500e+00   1.64866667e+00   3.68625000e-01   8.73666667e-01
   5.78716667e+00  -5.71708333e-01   5.31829167e+00   5.27500000e-01
   3.65850000e+00   1.55050000e+00  -6.37583333e-01   2.51408333e+00
   3.31620833e+00   2.91125000e-01  -2.49629167e+00  -6.33900000e+00
   5.63733333e+00  -3.08529167e+00  -1.57920833e+00   3.36141667e+00
  -1.42937500e+00   6.07262500e+00   1.88762500e+00   3.87162500e+00
   2.95000000e-01   5.80395833e+00  -3.59162500e+00   7.28333333e-02
  -5.17458333e-01  -3.01425000e+00  -1.10258333e+00  -3.89258333e+00
  -2.10491667e+00   1.12875000e-01   4.25525000e+00   3.03591667e+00
  -3.30166667e-01   3.31104167e+00  -5.49683333e+00   3.82641667e+00
   6.90187500e+00   2.49987500e+00  -1.88791667e+00  -5.60083333e-01
   8.60750000e-01   1.93670833e+00   3.39370833e+00  -4.12508333e+00
   2.57220833e+00   2.07750000e+00  -1.31700000e+00   1.33091667e+00
  -8.73333333e-02   9.54166667e-03   3.09662500e+00  -2.86250000e-01
   4.42058333e+00  -7.22833333e-01  -4.70958333e-01  -2.01450000e+00
  -7.07395833e+00  -1.88275000e+00  -7.91291667e-01   3.13666667e+00
   8.67208333e-01  -2.78950000e+00  -1.40291667e-01   4.13833333e-01
   3.90583333e-01  -8.75250000e-01  -2.13333333e+00  -1.31054167e+00
  -4.89750000e+00  -4.82000000e+00   1.30250000e+00   4.03500000e-01
  -2.47045833e+00  -5.91662500e+00  -8.48125000e-01  -8.41666667e-01
  -4.80320833e+00   1.33995833e+00   2.70008333e+00   3.26454167e+00
  -2.86250000e-01  -3.68075000e+00   9.48583333e-01   4.00079167e+00
  -1.24854167e+00   5.19816667e+00  -3.70208333e-01  -1.01541667e-01
   2.88091667e+00  -4.85166667e-01  -2.41620833e+00   2.24283333e+00
   2.46887500e+00   5.02958333e-01  -3.60712500e+00  -1.44229167e+00
   1.89083333e-01   4.38570833e+00   2.46500000e+00   1.58083333e-01
   2.30416667e-01  -2.38650000e+00   4.73704167e+00   4.99795833e+00
   1.89795833e+00  -8.93333333e-01  -5.50587500e+00  -8.31333333e-01
  -5.37500000e-02   4.79708333e-01  -9.86333333e-01   3.32912500e+00
  -1.65800000e+00  -5.18941667e+00   3.00879167e+00  -1.62183333e+00
   5.46295833e+00   1.59700000e+00   1.65254167e+00  -1.62312500e+00
   2.02970833e+00  -4.24458333e-01  -3.38883333e+00  -1.19687500e+00
   4.96825000e+00  -6.41458333e-01   4.24104167e+00   3.77862500e+00
   2.57220833e+00   3.45700000e+00  -1.34412500e+00   7.61291667e-01
   7.19120833e+00   3.77666667e-01   1.40583333e+00   3.99625000e-01
  -1.69416667e+00   5.97704167e+00  -2.80629167e+00   3.32654167e+00
   1.26762500e+00   1.20691667e+00  -3.85708333e-01   1.24308333e+00
  -3.30166667e-01  -6.41520833e+00   3.50220833e+00  -3.27129167e+00
   4.57083333e-02  -2.34000000e+00   3.75925000e+00  -7.04295833e+00
   1.85275000e+00   2.85120833e+00  -5.82879167e+00  -4.47254167e+00
   1.27408333e+00  -6.99583333e-01   1.75845833e+00  -1.96154167e+00
   3.11791667e-01  -1.56241667e+00   2.36812500e+00   4.53166667e+00
   3.77087500e+00   2.40170833e+00  -9.69541667e-01   3.41825000e+00
  -1.85691667e+00  -3.02200000e+00  -6.68583333e-01   1.90958333e+00
  -1.77941667e+00   2.44304167e+00  -8.27458333e-01  -2.85666667e+00
  -7.58287500e+00   1.21916667e-01   1.47300000e+00   2.25833333e+00
   4.82616667e+00  -3.07625000e+00   1.42262500e+00  -4.28395833e+00
   1.33737500e+00   2.55929167e+00  -6.47720833e+00   2.43658333e+00
   3.64687500e+00   8.83333333e-02   3.10954167e+00  -1.96154167e+00
   3.97237500e+00   3.05787500e+00   1.44329167e+00  -3.22737500e+00
  -1.06641667e+00   2.80791667e-01  -2.04420833e+00   1.63962500e+00
  -7.62420833e+00   1.30766667e+00  -2.51437500e+00   4.11833333e+00
  -4.26845833e+00  -2.91350000e+00  -3.74533333e+00  -2.89025000e+00
  -3.16150000e+00  -1.49008333e+00   2.70137500e+00  -1.98350000e+00
   4.37925000e+00  -3.74662500e+00  -1.10000000e+00   1.51691667e+00
   2.49212500e+00   2.02000000e-01   3.27291667e-01  -2.98841667e+00
   4.53875000e-01   1.91733333e+00  -3.44954167e+00  -1.76650000e+00
   2.92741667e+00  -2.04937500e+00   3.31166667e-01  -4.95500000e-01
  -1.11250000e-02  -1.84529167e+00  -2.27500000e-02  -4.66370833e+00
   3.41308333e+00  -3.71820833e+00  -4.05083333e-01  -6.54050000e+00
  -1.11550000e+00   1.61508333e+00   8.50416667e-01  -1.10775000e+00
   1.28700000e+00   1.89083333e-01   3.45829167e+00   1.25858333e+00
  -3.56320833e+00   2.37070833e+00   1.19787500e+00  -3.65750000e+00
  -2.59058333e+00   4.66600000e+00  -5.65250000e-01  -4.50291667e-01
   2.25187500e+00   2.16662500e+00  -1.47587500e+00  -7.82916667e-02
  -3.17441667e+00   2.80791667e-01   3.91812500e+00  -1.94862500e+00
  -1.58954167e+00   4.93466667e+00  -1.04575000e+00  -1.52625000e+00
   1.22370833e+00  -9.24333333e-01   7.34879167e+00  -1.41583333e-01
   2.67875000e-01  -5.22625000e-01   3.28779167e+00   2.73883333e+00
  -1.51720833e+00   1.82304167e+00   8.50416667e-01   5.00375000e-01
   1.67708333e+00   5.39062500e+00   3.33687500e+00   7.29000000e-01
   9.21458333e-01  -2.81791667e+00   1.78816667e+00   8.20708333e-01
  -4.87037500e+00   1.16750000e-01   1.11520833e+00  -5.63333333e-02
   6.32579167e+00   4.09895833e+00   1.19012500e+00   1.73133333e+00
  -1.26145833e+00  -5.47487500e+00   1.45362500e+00   4.64791667e+00
  -2.67841667e+00  -1.38675000e+00  -2.01000000e-01   4.41154167e+00
  -3.09500000e-01   1.28700000e+00   1.25858333e+00  -1.26404167e+00
   5.74000000e-01   3.17929167e+00   2.99458333e+00  -8.66208333e-01
   1.03833333e-01   2.44304167e+00  -2.01062500e+00  -2.59058333e+00
  -3.40500000e-01  -2.54795833e+00   3.20383333e+00   2.93258333e+00
   2.40558333e+00  -2.56345833e+00   1.45620833e+00  -1.45779167e+00
  -2.28125000e-01  -1.62570833e+00  -1.95379167e+00  -2.59704167e+00
  -2.47175000e+00  -1.12195833e+00   4.45158333e+00   1.50270833e+00
  -2.64870833e+00   2.77500000e+00   4.81066667e+00   2.96100000e+00
   7.00583333e-01  -4.10958333e+00   2.61416667e-01  -1.62054167e+00
  -2.84245833e+00   2.23958333e-01  -2.66291667e+00  -1.85045833e+00
   8.68500000e-01   3.07983333e+00  -9.66958333e-01  -1.72387500e+00
  -1.07287500e+00   2.24154167e+00   3.73791667e-01   3.59583333e-01
  -2.38650000e+00  -1.80654167e+00   3.81350000e+00   2.62258333e+00
   1.98320833e+00   7.60000000e-01   1.56858333e+00  -6.59541667e-01
   6.57120833e+00  -2.87733333e+00  -8.50770833e+00  -2.81404167e+00
   2.59804167e+00  -2.91866667e+00  -2.14108333e+00   3.47637500e+00
  -3.98625000e-01  -1.82850000e+00   5.79104167e+00  -6.37583333e-01
  -9.47583333e-01  -1.20462500e+00  -8.17125000e-01   6.53633333e+00
   6.98325000e+00  -1.45908333e+00  -9.46291667e-01  -8.30041667e-01
   2.39654167e+00  -3.06916667e-01  -1.16587500e+00  -9.39833333e-01
  -7.34458333e-01  -1.30925000e+00   8.10375000e-01   2.36295833e+00
   2.35908333e+00  -5.56270833e+00  -2.37100000e+00   1.90054167e+00
   6.45883333e+00   1.36450000e+00   6.69583333e-01   5.74325000e+00
  -5.08416667e-01   1.27150000e+00   4.38441667e+00  -1.81687500e+00
   2.17050000e+00  -7.82916667e-02  -7.33166667e-01   4.83583333e-01
  -1.24466667e+00  -3.28291667e+00  -7.92583333e-01   5.95958333e-01
   1.31670833e+00  -4.29687500e+00  -9.73416667e-01   1.50012500e+00
  -1.44166667e-01   4.80937500e+00   4.53683333e+00  -8.08083333e-01
   5.46875000e-01  -6.00125000e-01   5.02508333e+00   5.64958333e-01
   4.09637500e+00  -2.35937500e+00  -2.06875000e+00   1.88762500e+00
  -2.39941667e+00   1.94445833e+00  -4.06695833e+00   4.33404167e+00
   3.14958333e+00  -3.96750000e+00  -1.88920833e+00  -3.83058333e+00
  -1.14908333e+00  -4.68375000e-01  -9.69541667e-01  -1.62916667e-02
  -2.55958333e+00  -3.22737500e+00  -2.97291667e+00  -2.46141667e+00
   3.10500000e-01  -3.54770833e+00   4.65500000e-01   2.42754167e+00
  -7.99041667e-01  -2.52729167e+00   2.27254167e+00  -1.13487500e+00
  -1.33120833e+00  -3.37916667e-01  -2.88895833e+00   5.44487500e+00
   4.06408333e+00   1.95350000e+00  -3.25191667e+00  -1.95120833e+00
  -2.31675000e+00   2.17179167e+00   2.96875000e+00  -2.83858333e+00
   1.05966667e+00  -1.31958333e+00  -3.44825000e+00  -1.83108333e+00
  -6.02083333e-02   4.27333333e+00  -3.04137500e+00   7.35458333e-01
   3.18187500e+00  -4.78383333e+00  -5.23333333e+00   6.15333333e-01
   3.15000000e-02  -2.41879167e+00   2.95970833e+00  -3.87191667e+00
   2.29125000e-01  -4.25425000e+00  -2.62933333e+00   5.33958333e-01]

0.004

* If p value is 0.05, it is statistically significant to reject the null value

* If p value is 0.01, it is highly statistically significant to reject the null value

In [95]:
def transition_probability(table):
    increase_to_increase = 0
    increase_to_decrease = 0
    increase_to_unchange = 0
    decrease_to_increase = 0
    decrease_to_decrease = 0
    decrease_to_unchange = 0
    unchange_to_increase = 0
    unchange_to_decrease = 0
    unchange_to_unchange = 0

    #check the following action of the price after increasing/decreasing/unchange
    for i in range(len(table['Comparison'])-1):
        if table['Comparison'][i] == "Decreasing":
            if table['Comparison'][i+1]=="Decreasing":
                decrease_to_decrease +=1
            elif table['Comparison'][i+1]=="Increasing":
                decrease_to_increase+=1
            else:
                decrease_to_unchange+=1
        elif table['Comparison'][i] == "Increasing":
            if table['Comparison'][i+1]=="Increasing":
                increase_to_increase +=1
            elif table['Comparison'][i+1]=="Decreasing":
                increase_to_decrease+=1
            else:
                increase_to_unchange+=1
        else:
            if table['Comparison'][i+1]=="Unchanged":
                unchange_to_unchange +=1
            elif table['Comparison'][i+1]=="Increasing":
                unchange_to_increase+=1
            else:
                unchange_to_decrease+=1
    increase = increase_to_increase+increase_to_decrease+increase_to_unchange
    decrease = decrease_to_decrease+decrease_to_increase+decrease_to_unchange 
    unchange = unchange_to_decrease+unchange_to_increase+unchange_to_unchange

    #find the probability
    if increase != 0:
        increase_to_increase_prob = round(increase_to_increase/increase,2)
        increase_to_decrease_prob = round(increase_to_decrease/increase,2)
        increase_to_unchange_prob = round(increase_to_unchange/increase,2)
    else:   
        increase_to_increase_prob = 0
        increase_to_decrease_prob = 0
        increase_to_unchange_prob = 0 

    if decrease!=0:
        decrease_to_decrease_prob = round(decrease_to_decrease/decrease,2)
        decrease_to_increase_prob = round(decrease_to_increase/decrease,2)
        decrease_to_unchange_prob = round(decrease_to_unchange/decrease,2)
    else:
        decrease_to_decrease_prob = 0
        decrease_to_increase_prob = 0
        decrease_to_unchange_prob = 0
    if unchange!=0:
        unchange_to_decrease_prob = round(unchange_to_decrease/unchange,2)
        unchange_to_increase_prob = round(unchange_to_increase/unchange,2)
        unchange_to_unchange_prob = round(unchange_to_unchange/unchange,2)
    else:
        unchange_to_decrease_prob = 0
        unchange_to_increase_prob = 0
        unchange_to_unchange_prob = 0
    return increase_to_increase_prob,increase_to_decrease_prob,increase_to_unchange_prob,decrease_to_decrease_prob,decrease_to_increase_prob,decrease_to_unchange_prob,unchange_to_decrease_prob,unchange_to_increase_prob,unchange_to_unchange_prob

In [99]:
transition_probability(price_table)

(0.44, 0.56, 0.0, 0.36, 0.64, 0.0, 0, 0, 0)

In [9]:
def get_state_index(index_state,grid_size):
    return index_state[0] * grid_size[1] + index_state[1] #get the index to find the corresponding profit and value

In [10]:
def get_price(action,price):
    if action == 0:
        price +=1
    elif action == 1:
        price
    elif action == 2:
        price -= 1
    return price

In [11]:
def get_next_state1(purchase_prob, customers_demand,inventory,day):
    #x is price, y is reman
    remaining_inv = inventory - (purchase_prob*customers_demand) #find the remaining inventory for each action
    day-=1 #decrement day bt 1, we have 30 days remaining
    return (day,remaining_inv) #next state

In [12]:
def get_reward1(price, purchase_prob, customers_demand):
    reward = price*purchase_prob*customers_demand
    return reward

In [13]:
price_probability = dict()

In [14]:
def get_purchase_probability(price,data):
    global price_probability
    if price in price_probability.keys():
        purchase_probability = price_probability[price] #look into the dictionary with price-purchase probability pair to see if we have already have them
    else:
        data_match = data.where('Price',are.below_or_equal_to(price)).column('Price')
        if len(data_match) == 0:
            closest_match = min(data.where('Price',are.above_or_equal_to(price)).column('Price')) #sometimes action -1 dollar make the price to be the smallest, this is when we take the closest larget price
        else:
            closest_match = max(data_match) #find the closest smaller price to the new price
    #get purchase probability
        purchase_probability = data.where('Price',closest_match).column('Purchase Probability')[0]
        price_probability[price]=purchase_probability
    return purchase_probability

In [11]:
get_purchase_probability(24.3,simulated_dataset)

0.44

In [15]:
def get_value(price, day_remain, inv_remain,purchase_porb,customers_demand,data, depth):
    
    if day_remain < 0 or inv_remain < 0 or depth >10:
        return get_reward1(price,purchase_porb,customers_demand) #base case
    else:
        reward = get_reward1(price,purchase_porb,customers_demand) #get the reward

        #find the purchase probability at increased/unchaged/decreased price
        purchase_prob_at_increased_price = get_purchase_probability(price+1,data)
        purchase_prob_at_unchanged_price = get_purchase_probability(price,data)
        purchase_prob_at_decreased_price = get_purchase_probability(price-1,data)
        
        value= reward + 0.9 / 3 * (
            get_value(price + 1, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_increased_price,purchase_prob_at_increased_price,30,data,depth+1) 
            + get_value(price, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_unchanged_price,purchase_prob_at_unchanged_price,30,data,depth+1) 
            + get_value(price - 1, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_decreased_price,purchase_prob_at_decreased_price,30,data,depth+1))

        return value

In [16]:
def get_value_2(price, day_remain, inv_remain,purchase_porb,customers_demand,data, depth):
    
    if day_remain < 0 or inv_remain < 0 or depth >10:
        return get_reward1(price,purchase_porb,customers_demand) #base case
    else:
        reward = get_reward1(price,purchase_porb,customers_demand) #get the reward

        #find the purchase probability at increased/unchaged/decreased price
        purchase_prob_at_increased_price = get_purchase_probability(price+1,data)
        purchase_prob_at_unchanged_price = get_purchase_probability(price,data)
        purchase_prob_at_decreased_price = get_purchase_probability(price-1,data)
        
        value= reward + max(
            get_value(price + 1, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_increased_price,purchase_prob_at_increased_price,30,data,depth+1) 
            ,get_value(price, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_unchanged_price,purchase_prob_at_unchanged_price,30,data,depth+1) 
            ,get_value(price - 1, day_remain - 1, inv_remain - customers_demand * purchase_prob_at_decreased_price,purchase_prob_at_decreased_price,30,data,depth+1))

        return value

In [17]:
def value_iteration(data):
    date_range = data.column('Date') #x
    inventory_range = data.column('Remaining Inventory') #y
    chosen_price = data.column('Price')[0] #set the initial price to the first price in the dataset
    grid_size = (len(date_range),len(inventory_range))
    num_actions = 3
    Value = np.zeros(grid_size[0]) #create a place holder for calculated value
   
    for day in range(grid_size[0]):
        #for inv in range(grid_size[1]):
            value_state = (date_range[day],inventory_range[day]) #do i need this?
            #state_index = get_state_index(index_state,grid_size) #get the index of the location to update this location later
            v = Value[day] #get the number out (0 most of the time until loop through the second time)
            print(f'This is v: {v}')
            max_value = float('-inf')
                   
            for action in range(num_actions): #
                    print(f'Action: {action}')
                    print('Price last stage', chosen_price)
                    price = chosen_price #update the price to the price yield the most value
                    price = get_price(action,price) #update the price
                    
                    #get purchase probability
                    purchase_probability = get_purchase_probability(price,data)
                    
                    #get next state
                    next_state = get_next_state1(purchase_probability,30,value_state[1],value_state[0]) #if took that action, the new pair (x,y) is the remaining day and the remaining inventory
                    print(f'Next state {next_state}')


                    value = get_value(price,next_state[0],next_state[1],purchase_probability,30,data,0) #calcute with the reward of the current pair and the value of the next pair
                    print(f'This is value {value}')
                    if value > max_value: #if find bigger value, update
                        max_value = value
                        chosen_price = price #keep the price the yield the most value
                    
                    Value[day] = max_value #update the value in the current pair whenever we found a bigger value
    print(Value)

In [ ]:
value_iteration(simulated_dataset)

In [18]:
action_dict = {
    0: "Increase $1",
    1:"Keep price",
    2:"Decrease $1"}

In [52]:
action_dict

{0: 'Increase $1', 1: 'Keep price', 2: 'Decrease $1'}

In [21]:
def policy_iteration(data):
    date_range = data.column('Date') #x
    inventory_range = data.column('Remaining Inventory') #y
    chosen_price = data.column('Price')[0] #set the initial price to the first price in the dataset
    grid_size = (len(date_range),len(inventory_range))
    num_actions = 3
    optimal_policy = np.empty(shape=(0),dtype=tuple)
   
    for day in range(grid_size[0]):
        value_state = (date_range[day],inventory_range[day])
            
        max_value = float('-inf')
        price = chosen_price #update the price to the price yield the most value
        #print(chosen_price)
        for action in range(num_actions): 
            print(f'Action: {action}')
            print('Price last stage', price)
            new_price = get_price(action,price) #update the price
            print('Price this stage:', new_price)
            #get purchase probability
            purchase_probability = get_purchase_probability(new_price,data) #get purchase probability at the price after action taken
                    
            #get next state
            next_state = get_next_state1(purchase_probability,30,value_state[1],value_state[0]) #if took that action, the new pair (x,y) is the remaining day and the remaining inventory
            #print(f'Next state {next_state}')

            #value = get_value(new_price,next_state[0],next_state[1],purchase_probability,30,data,0) #calcute with the reward of the current pair and the value of the next pair
            value = get_value_2(new_price,next_state[0],next_state[1],purchase_probability,30,data,0) #calcute with the reward of the current pair and the value of the next pair
            print(f'This is value {value}')
            if value > max_value: #if find bigger value, update
                max_value = value
                chosen_price = new_price #keep the price the yield the most value
                best_action = action
                revenue = chosen_price * purchase_probability * 30 #calculate revenue if the action is taken in the next stage
        #print(chosen_price)
        optimal_policy = np.append(optimal_policy,[value_state[0],action_dict[best_action],chosen_price,revenue]) #add to the optimal policy
    print(optimal_policy)

In [17]:
simulated_dataset = get_dataset(1000)

In [22]:
policy_iteration(simulated_dataset)

Action: 0
Price last stage 24.93
Price this stage: 25.93
This is value 1842.3035533156958
Action: 1
Price last stage 24.93
Price this stage: 24.93
This is value 2094.584445301933
Action: 2
Price last stage 24.93
Price this stage: 23.93
This is value 2347.6836400149205
Action: 0
Price last stage 23.93
Price this stage: 24.93
This is value 2094.584445301933
Action: 1
Price last stage 23.93
Price this stage: 23.93
This is value 2347.6836400149205
Action: 2
Price last stage 23.93
Price this stage: 22.93
This is value 2528.411072512648
Action: 0
Price last stage 22.93
Price this stage: 23.93
This is value 2347.6836400149205
Action: 1
Price last stage 22.93
Price this stage: 22.93
This is value 2528.411072512648
Action: 2
Price last stage 22.93
Price this stage: 21.93
This is value 2675.2362521899813
Action: 0
Price last stage 21.93
Price this stage: 22.93
This is value 2528.411072512648
Action: 1
Price last stage 21.93
Price this stage: 21.93
This is value 2675.2362521899813
Action: 2
Price last stage 21.93
Price this stage: 20.93
This is value 2795.1724780878735
Action: 0
Price last stage 20.93
Price this stage: 21.93
This is value 2675.2362521899813
Action: 1
Price last stage 20.93
Price this stage: 20.93
This is value 2795.1724780878735
Action: 2
Price last stage 20.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 0
Price last stage 19.93
Price this stage: 20.93
This is value 2795.1724780878735
Action: 1
Price last stage 19.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 2
Price last stage 19.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2825.0118400358183
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2847.064840035818
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2827.2648400358185
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2703.1634877838283
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2725.216487783828
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2705.4164877838284
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2567.1783386632196
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2589.2313386632195
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2569.43133866322
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2415.4057422797996
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2437.4587422797995
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2417.6587422797998
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2246.0050341689994
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2268.0580341689997
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2248.2580341689995
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 2056.9056045899997
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 2078.9586045899996
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 2059.15860459
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 1845.8374982999999
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 1867.8904983
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 1848.0904983
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 1610.1000149999998
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 1632.1530149999999
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 1612.3530149999997
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 1347.2043899999999
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 1369.25739
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 1349.45739
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 1052.3517
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 1074.4047
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 1054.6046999999999
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 727.575
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 749.628
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 729.828
Action: 0
Price last stage 18.93
Price this stage: 19.93
This is value 352.76099999999997
Action: 1
Price last stage 18.93
Price this stage: 18.93
This is value 374.814
Action: 2
Price last stage 18.93
Price this stage: 17.93
This is value 355.014
['30' 'Decrease $1' '23.93' '272.802' '29' 'Decrease $1' '22.93' '323.313'
 '28' 'Decrease $1' '21.93' '309.213' '27' 'Decrease $1' '20.93' '370.461'
 '26' 'Decrease $1' '19.93' '352.761' '25' 'Decrease $1' '18.93' '374.814'
 '24' 'Keep price' '18.93' '374.814' '23' 'Keep price' '18.93' '374.814'
 '22' 'Keep price' '18.93' '374.814' '21' 'Keep price' '18.93' '374.814'
 '20' 'Keep price' '18.93' '374.814' '19' 'Keep price' '18.93' '374.814'
 '18' 'Keep price' '18.93' '374.814' '17' 'Keep price' '18.93' '374.814'
 '16' 'Keep price' '18.93' '374.814' '15' 'Keep price' '18.93' '374.814'
 '14' 'Keep price' '18.93' '374.814' '13' 'Keep price' '18.93' '374.814'
 '12' 'Keep price' '18.93' '374.814' '11' 'Keep price' '18.93' '374.814'
 '10' 'Keep price' '18.93' '374.814' '9' 'Keep price' '18.93' '374.814' '8'
 'Keep price' '18.93' '374.814' '7' 'Keep price' '18.93' '374.814' '6'
 'Keep price' '18.93' '374.814' '5' 'Keep price' '18.93' '374.814' '4'
 'Keep price' '18.93' '374.814' '3' 'Keep price' '18.93' '374.814' '2'
 'Keep price' '18.93' '374.814' '1' 'Keep price' '18.93' '374.814' '0'
 'Keep price' '18.93' '374.814']

In [ ]:
def customer_demand(price):
    return round((-1/900) * price**2 +1,2)


def value(price, day_remain, inv_remain,data):
    if day_remain < 0 or inv_remain < 0:
        return 0
    else:
        print(price,day_remain, inv_remain)
        return price * 30 * customer_demand(price) + 0.3 / 3 * (value(price + 1, day_remain - 1, inv_remain - 30 * get_purchase_probability(price+1,data),data) 
                                                                + value(price, day_remain - 1, inv_remain - 30 * get_purchase_probability(price,data),data) 
                                                                + value(price - 1, day_remain - 1, inv_remain - 30 * get_purchase_probability(price-1,data),data))

In [ ]:
def value1(price, day_remain, inv_remain,data):
    global price_value
    if price in price_value.keys():
        return price_value[price]
    elif day_remain < 0 or inv_remain < 0:
        return 0
    else:
        print(price,day_remain, inv_remain)
        value = price * 30 * get_purchase_probability(price,data) + 0.3 / 3 * (value1(price + 1, day_remain - 1, inv_remain - 30 * get_purchase_probability(price+1,data),data) 
                                                                + value1(price, day_remain - 1, inv_remain - 30 * get_purchase_probability(price,data),data) 
                                                                + value1(price - 1, day_remain - 1, inv_remain - 30 * get_purchase_probability(price-1,data),data))
        price_value[price] = value
        return value

In [ ]:
value1(15, 30, 1000,simulated_dataset)

483.27834133453723